export const documents = [
  { tag: "Tender", title: "OEM Authorization Certificate / Authorization Letter", templates: 3 },
  { tag: "Tender", title: "Acceptance of Bid Terms and Conditions (ATC)", templates: 4 },
  { tag: "Tender", title: "Performance Statement of Bidder for Bid Number", templates: 3 },
  { tag: "Tender", title: "Datasheet Declaration for Bid", templates: 3 },
  { tag: "Tender", title: "Scope of Supply and Cost Estimation Declaration for Bid", templates: 2 },
  { tag: "Tender", title: "Warranty Declaration for Bid", templates: 3 },
  { tag: "Tender", title: "Lowest Price Declaration for Bid", templates: 3 },
  { tag: "Tender", title: "Non-Blacklisting and Non-Debarred Declaration for Bid", templates: 5 },
  { tag: "Tender", title: "Non-Liquidation Declaration for Bid", templates: 3 },
  { tag: "Tender", title: "Declaration for Service, Repair, and Maintenance for Bid", templates: 3 },
  { tag: "Tender", title: "Declaration Regarding Insolvency for Bid", templates: 3 },
  { tag: "Tender", title: "Declaration Regarding Sample and Advance Sampling for Bid", templates: 3 },
  { tag: "Tender", title: "Declaration of Manufacturer Status for Bid", templates: 3 },
  { tag: "Tender", title: "Non-Relation Declaration for Bid", templates: 3 },
  { tag: "Tender", title: "MSME Exemption Declaration for EMD for Bid", templates: 3 },
  { tag: "Tender", title: "MSME Exemption Declaration for Turnover for Bid", templates: 3 },
  { tag: "Tender", title: "Declaration of Financial Capacity for Bid", templates: 3 },
  { tag: "Tender", title: "Declaration of Compliance with Make in India (MII) for Bid", templates: 3 },
  { tag: "Tender", title: "Declaration of Non-Corruption and Anti-Bribery Compliance for Bid", templates: 3 },
  { tag: "Tender", title: "Declaration of Compliance with Integrity Pact for Bid", templates: 3 },
  { tag: "Tender", title: "Declaration of Land Border Sharing Compliance for Bid", templates: 3 },
  { tag: "Vendor_Assessment", title: "Beneficial Ownership Declaration", templates: 1 },
  { tag: "Vendor_Assessment", title: "List of Partners", templates: 1 },
  { tag: "Vendor_Assessment", title: "List of Directors", templates: 1 },
  { tag: "Vendor_Assessment", title: "List of Shareholders", templates: 1 },
  { tag: "Vendor_Assessment", title: "RBI Approval", templates: 2 },
  { tag: "Vendor_Assessment", title: "JV Member Details and Joint Venture Agreement", templates: 2 },
  { tag: "Vendor_Assessment", title: "BEN-2 Filing Acknowledgement as per MCA Guidelines", templates: 2 },
  { tag: "Vendor_Assessment", title: "Authorization Letter in Favor of Signing Official", templates: 1 },
  { tag: "Vendor_Assessment", title: "Import Export Code (IEC)", templates: 2 },
  { tag: "Vendor_Assessment", title: "Declaration Regarding Debarment or Blacklisting Status", templates: 1 },
  { tag: "Vendor_Assessment", title: "Stage-wise / Component-wise Inspection Plan (Quality Assurance Plan)", templates: 2 },
  { tag: "Vendor_Assessment", title: "Approved Suppliers List", templates: 1 },
  { tag: "Vendor_Assessment", title: "Safety Standard Operating Procedures (SOP) Manual", templates: 2 },
  { tag: "Vendor_Assessment", title: "Manufacturer with Machines List", templates: 1 }
];
